name: Deploy proto files to typescript and golang

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: Connectrpc Go package installation
        run: |
          git config --global user.email "max@jeschek.dev"
          git config --global user.name "maxischmaxi"
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
          [ -n "$(go env GOBIN)" ] && export PATH="$(go env GOBIN):${PATH}"
          [ -n "$(go env GOPATH)" ] && export PATH="$(go env GOPATH)/bin:${PATH}"
      - name: Generate Go code
        run: |
          buf generate --template buf.gen.go.yaml
      - name: Clone Go repo
        run: |
          git clone https://github.com/maxischmaxi/jstreams-go.git
      - name: Remove old Go files
        run: |
          cd jstreams-go
          find . -mindepth 1 ! -name "go.mod" -exec rm -rf {} +
      - name: Copy Go files
        run: |
          cp -r gen-go/* jstreams-go/
      - name: Commit Go files
        run: |
          cd jstreams-go
          git add .
          git commit -m "$GITHUB_SHA"
          git remote set-url origin https://maxischmaxi:${{ secrets.GH_TOKEN }}@github.com/maxischmaxi/jstreams-go.git
          git push -u origin main
          git tag -a "$GITHUB_SHA" -m "$GITHUB_SHA"
          git push origin "$GITHUB_SHA"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Clone Typescript repo
        run: |
          git clone https://github.com/maxischmaxi/jstreams-ts.git
      - name: Connectrpc Node package installation
        run: |
          cd jstreams-ts
          npm ci
          npx buf generate --template ../buf.gen.ts.yaml
          git add .
          git commit -m "$GITHUB_SHA"
          git remote set-url origin https://maxischmaxi:${{ secrets.GH_TOKEN }}@github.com/maxischmaxi/jstreams-ts.git
          git push -u origin main
